# Generated by Django 4.2.16 on 2024-12-07 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='producto_ppid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='pedidos.PedidoProducto', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pid', to=settings.AUTH_USER_MODEL, verbose_name='Id del usuario'),
        ),
    ]
