# Generated by Django 4.2.16 on 2024-12-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='sin Direccion', max_length=30, verbose_name='direccion'),
        ),
    ]
