# Generated by Django 4.2.17 on 2024-12-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('pedidos', '0004_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidoproducto',
            unique_together={('pedido_ppid', 'producto_ppid')},
        ),
        migrations.AddConstraint(
            model_name='pedidoproducto',
            constraint=models.UniqueConstraint(fields=('pedido_ppid', 'producto_ppid'), name='unique_pedido_producto'),
        ),
    ]
