# Generated by Django 4.2.16 on 2024-12-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_favoritos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritos',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
    ]
