# Generated by Django 4.2.16 on 2024-12-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_favoritos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto_producto',
        ),
    ]
