# Generated by Django 4.2.16 on 2024-12-14 02:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_foto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_producto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
